### ISSUE TITLE
Not working any more?

### ISSUE THREAD

**Issue by markosole** [wbyoung/yahoo-finance-stream#1]
I am wondering does this work any more? Looks easy to use but it's throwing an errors

`at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'query.yahooapis.com'`

Is there solution for this? Thx

**Comment by wbyoung** [comment]
I think Yahoo finance may have shut down some APIs like what this uses. I haven't tried using it in quite a long time.

**Comment by markosole** [comment]
Yeah I can see that, and other solutions stopped working too. :/
